fastlane_version '2.53.1'

before_all do
end

platform :ios do
   # iOS Lanes
   desc "Description of what the lane does"
    lane :generate_ipa_develop do
    xcbuild(
      project: "./ios/fastlaneProj.xcodeproj",
      scheme: "fastlaneProj",
    )
    end
end

platform :android do
  # Android Lanes
  desc 'Build the Android application.'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end
  
  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
  end

end
